// Generated by npm run knowledge:sync. Edit .project/changes/ records instead.
import type { Change } from "@/types";
import record0 from "../../.project/changes/availability-check.json";
import record1 from "../../.project/changes/waitlists-added.json";
import record2 from "../../.project/changes/pickup-reminders.json";
import record3 from "../../.project/changes/member-privacy.json";
import record4 from "../../.project/changes/reminder-dedup.json";
import record5 from "../../.project/changes/photo-previews.json";
export const changes: Change[] = [record0 as Change, record1 as Change, record2 as Change, record3 as Change, record4 as Change, record5 as Change];
