// Generated by npm run knowledge:sync. Edit .project/tasks/ records instead.
import type { Task } from "@/types";
import record0 from "../../.project/tasks/BRW-43.json";
import record1 from "../../.project/tasks/BRW-42.json";
import record2 from "../../.project/tasks/BRW-44.json";
import record3 from "../../.project/tasks/BRW-45.json";
import record4 from "../../.project/tasks/BRW-46.json";
import record5 from "../../.project/tasks/BRW-47.json";
import record6 from "../../.project/tasks/BRW-48.json";
import record7 from "../../.project/tasks/BRW-49.json";
import record8 from "../../.project/tasks/BRW-38.json";
import record9 from "../../.project/tasks/BRW-35.json";
import record10 from "../../.project/tasks/BRW-36.json";
import record11 from "../../.project/tasks/BRW-37.json";
export const tasks: Task[] = [record0 as Task, record1 as Task, record2 as Task, record3 as Task, record4 as Task, record5 as Task, record6 as Task, record7 as Task, record8 as Task, record9 as Task, record10 as Task, record11 as Task];
