// Generated by npm run knowledge:sync. The repository records are the source of truth.
import type { Project, Developer, Milestone, Decision, Notification, OverviewData } from "@/types";
import projectData from "../../.project/project.json";
export const project = projectData as Project;
import projectsData from "../../.project/projects.json";
export const projects = projectsData;
import developersData from "../../.project/developers.json";
export const developers = developersData as Developer[];
import milestonesData from "../../.project/milestones.json";
export const milestones = milestonesData as Milestone[];
import notificationsData from "../../.project/notifications.json";
export const notifications = notificationsData as Notification[];
// Generated by npm run knowledge:sync. Edit .project/decisions/ records instead.
import record0 from "../../.project/decisions/adr-017.json";
import record1 from "../../.project/decisions/adr-018.json";
export const decisions: Decision[] = [record0 as Decision, record1 as Decision];

import manifestData from "../../.project/manifest.json";
export const knowledge = manifestData;

import overviewData from "../../.project/overview.json";
export const overview = overviewData as OverviewData;
